config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projekts#index"

  #get ':projekt_id', to: 'user_storys#index'

  resources :projekts
  resources :user_storys 
  resources :sprints
  resources :scrumboards
  resources :planpokers 
  resources :burndowncharts
  resources :sprintplans
  resources :sprintreviews
  resources :sprintretros
  resources :roadmaps

  get '/createfields', to: "planpokers#createfields"
  post '/createfields', to: "planpokers#createfields"


  get '/checkpoker', to: "planpokers#checkpoker"
  post '/checkpoker', to: "planpokers#checkpoker"


  get '/pokersuccess', to: "planpokers#pokersuccess"
  post '/pokersuccess', to: "planpokers#pokersuccess"

  get '/setsprint', to: "sprintplans#setsprint"
  post '/setsprint', to: "sprintplans#setsprint"


  get '/setreview', to: "sprintreviews#setreview"
  post '/setreview', to: "sprintreviews#setreview"

  
  get '/setretros', to: "sprintretros#setretros"
  post '/setretros', to: "sprintretros#setretros"


  

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_backlog.rb
class ProductBacklog < ApplicationRecord
	belongs_to :projekt
end

app/models/projekt.rb
class Projekt < ApplicationRecord

	belongs_to :user
	has_many :user_stories
	has_many :sprints
end

app/models/sprint.rb
class Sprint < ApplicationRecord
	
	belongs_to :projekt
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :projekts
end

app/models/user_story.rb
class UserStory < ApplicationRecord
	belongs_to :projekt
	
end

app/controllers/projekts_controller.rb
class ProjektsController < ApplicationController
	before_action :find_projekt, only: [:show, :edit, :update, :destroy, :getProjektId]
	before_action :authenticate_user!
	def index
		@projekts = current_user.projekts
	end

	def new
		@projekt = current_user.projekts.build
	end

	def create
		@projekt = current_user.projekts.build(projekt_params)
    	if @projekt.save
      		redirect_to root_path
    	else
     		render 'new'  #wenn es nicht klappt, die view new wird nochmal mit den eingegebenen Daten geladen, noch mal versuchen
    	end
	end

	def show
    @id = @projekt.id
  end

	def edit
	end

	def update
	if @projekt.update(projekt_params)
		redirect_to projekt_path(@projekt)
	else
		render 'edit'
	end
	end

	def destroy
		@projekt.destroy
  	redirect_to root_path
	end


  def find_projekt
  	@projekt = Projekt.find(params[:id])
	end

	def projekt_params
		params.require(:projekt).permit(:name)
	end

  def getProjektId
    redirect_to :controller => 'user_storys', :action => 'index', @projekt => @projekt
  end
end

app/controllers/roadmaps_controller.rb
class RoadmapsController < ApplicationController

	def index
		@projekt = Projekt.find(params[:format])
		@projekt_name = @projekt.name
	end
end

app/controllers/sprintreviews_controller.rb
class SprintreviewsController < ApplicationController

	rescue_from ActiveRecord::RecordNotFound, with: :dude_where_is_my_record

	def dude_where_is_my_record
		@projekt_id = params[:projekt_id]
		@sprint_id = params[:sprint_id]
		@userstory_id = params[:userstory_id]
    	flash[:notice] = "Dude where is my record !!!! no User Story with id = " + @userstory_id.to_s + "  ;-("
    	redirect_to sprintplans_path(sprint_id: @sprint_id, projekt_id: @projekt_id)
  	end

	def index
		@projekt = Projekt.find(params[:projekt_id])
		@projekt_name = @projekt.name
		@projekt_id = params[:projekt_id]
		@sprint_id = params[:sprint_id]
		@sprint = Sprint.find(@sprint_id)
		@sprint_number = @sprint.sprintnumber

		@userstories = @projekt.user_stories.where(status: "done").where(sprintnumber: @sprint_number).where(accepted: nil).or(@projekt.user_stories.where(status: "done").where(sprintnumber: @sprint_number).where(accepted: false))

		
	end

	def setreview

		@sprint_id = params[:sprint_id]
		@sprintnumber = Sprint.find(@sprint_id).sprintnumber
		@projekt_id = params[:projekt_id] 
		@projekt = Projekt.find(params[:projekt_id])
		@projekt_name = @projekt.name
		@userstory_id = params[:userstory_id].to_i
		@userstory = UserStory.find(@userstory_id)
		@userstories = @projekt.user_stories
		@reviewcomment = params[:reviewcomment] 
		@accepted = params[:accepted] 

		#if @userstory.projekt_id !=  @projekt_id 
			#flash[:notice] = "Die User Story gehört nicht den aktuellen Sprint, bitte nur die User Story links auswählen"
			#redirect_to sprintplans_path(sprint_id: @sprint_id, projekt_id: @projekt_id)
		@userstoriesToRev = @projekt.user_stories.where(status: "done").where(sprintnumber: @sprintnumber)
		unless @userstoriesToRev.include?(@userstory)
			flash[:notice] = "Die User Story gehört nicht in den aktuellen Sprint, bitte nur die User Stories links auswählen."
			redirect_to sprintreviews_path(sprint_id: @sprint_id, projekt_id: @projekt_id)
		else
			if @accepted == "false"
				flash[:notice] = "Leider wurde die User Story nicht abgenommen, versuche Sie den Kunden zufrieden zu stellen."
			else	
				flash[:notice] = "Super gemacht! Die User Story wurde abgenommen und archiviert."
			end
			@userstory.accepted = @accepted
			@userstory.reviewcomment = @reviewcomment
			@userstory.save
			redirect_to sprintreviews_path(sprint_id: @sprint_id, projekt_id: @projekt_id)
		end
	end
		
	
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
	before_action :find_sprint, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	
	def index
		@projekt = Projekt.find(params[:projekt_id])
		@projekt_id = @projekt.id
		@sprints = Sprint.where(projekt_id: @projekt_id)
	end

	def new
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprints =  projekt.sprints.build
		
	end

	def create
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprint = projekt.sprints.build(sprint_params) #UserStory.new(userstorie_params)
    	if @sprint.save
      		redirect_to sprints_path(projekt_id: @projekt_id)
    	else
     		render 'new'  
    	end
	end

	def show 
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprint_id = params[:id] 
  	end

  	def edit
  		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
	end

	def update
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		if @sprint.update(sprint_params)
			redirect_to sprint_path(@sprint,projekt_id: @projekt_id)
		else
			render 'edit'
		end
	end

	def destroy
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprint.destroy
  		redirect_to sprints_path(projekt_id: @projekt_id)
	end







	def find_sprint
  		@sprint = Sprint.find(params[:id])
	end

	def sprint_params
		params.require(:sprint).permit(:sprintnumber)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burndowncharts_helper.rb
module BurndownchartsHelper
end

app/helpers/planpokers_helper.rb
module PlanpokersHelper
end

app/helpers/product_backlog_helper.rb
module ProductBacklogHelper
end

app/helpers/projekts_helper.rb
module ProjektsHelper
end

app/helpers/roadmaps_helper.rb
module RoadmapsHelper
end

app/helpers/scrumboards_helper.rb
module ScrumboardsHelper
end

app/helpers/sprintplans_helper.rb
module SprintplansHelper
end

app/helpers/sprintretros_helper.rb
module SprintretrosHelper
end

app/helpers/sprintreviews_helper.rb
module SprintreviewsHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/user_storys_helper.rb
module UserStorysHelper
end

app/views/sprintreviews/index.html.erb
<h1><%= link_to @projekt_name, projekt_path(@projekt)%> - <%= link_to "Sprint "+ @sprint_number, sprint_path(projekt_id: @projekt_id, id: @sprint_id)%> -  Sprint Review</h1>

<div class="row">

  		<div class="col-md-2 list">
  		 	<p class="ptitle">Sprint Backlog</p>
        	<% if @userstories.count > 0  %>
          		<div class="listcard">
	      		 	<% @userstories.each do |userstorie| %>
	      		 	 	<p> 
	      		 	 		<span class="userstory_id"><%= userstorie.id %> -  </span> 
	      		 	 		<%= link_to userstorie.title, user_story_path(userstorie, projekt_id: @projekt_id) %> <br>
	      		 	 		<%if userstorie.sprintnumber != "" %>
	      		 	 			<% if userstorie.sprintnumber != ("" || nil) %>
	      		 	 				<span class="badge">sprint: <%= userstorie.sprintnumber %></span>
	      		 	 				<span class = "badge"><%= userstorie.status %></span>
	      		 	 			<% end %>
	      		 	 		<% end %>
	      		 	 	</p>
	            	<% end %>
        		</div>
        	<% end %>
  		</div>
  		

  		<div class="col-md-2">
	  		<%= form_tag(:action => 'setreview') do %>

	  			<div >
					<label> User Story Nummer eingeben: </label>
		  			<%= text_field_tag :userstory_id, params[:userstory_id], class: "form-control", required: "true", type: "number", min: "1" %>	

	  			</div>



				<div class = "acceptask">
					<label> User Story vom Product Owner abgenommen?</label>
		  			ja  <%= check_box_tag 'accepted', 'true' %>
		  			nein  <%= check_box_tag 'accepted', 'false' %>
		  			<%= hidden_field_tag "projekt_id", @projekt_id %>
		  			<%= hidden_field_tag "sprint_id", @sprint_id %>
		  		</div>
		 </div>
		  			
				


				<div class="col-md-2" class="form-group">
					<label> User Story Informationen festhalten: </label>
					<%= text_area_tag 'reviewcomment', nil, class: 'form-control' %>

					<%= submit_tag "Bestätigen", class: "btn btn-default" %>
					
				</div>

				

				
			<% end %>



		


</div>



<div class = "crud">
			<p><%= link_to "Zurück", sprint_path(projekt_id: @projekt_id, id: @sprint_id) %>
		<!--	<p><%= link_to "Zum Sprint Überblick", setreview_path(projekt_id: @projekt_id, id: @sprint_id) %> -->
</div>