config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projekts#index"

  #get ':projekt_id', to: 'user_storys#index'

  resources :projekts
  resources :user_storys 
  resources :sprints
  resources :scrumboards
  resources :planpokers 
  resources :burndowncharts
  resources :sprintplans
  resources :sprintreviews
  resources :sprintretros
  resources :roadmaps

  get '/createfields', to: "planpokers#createfields"
  post '/createfields', to: "planpokers#createfields"


  get '/checkpoker', to: "planpokers#checkpoker"
  post '/checkpoker', to: "planpokers#checkpoker"


  get '/pokersuccess', to: "planpokers#pokersuccess"
  post '/pokersuccess', to: "planpokers#pokersuccess"

  get '/setsprint', to: "sprintplans#setsprint"
  post '/setsprint', to: "sprintplans#setsprint"


  get '/setreview', to: "sprintreviews#setreview"
  post '/setreview', to: "sprintreviews#setreview"

  
  get '/setretros', to: "sprintretros#setretros"
  post '/setretros', to: "sprintretros#setretros"


  

  

end

app/models/user_story.rb
class UserStory < ApplicationRecord
	belongs_to :projekt
	
end

app/controllers/user_storys_controller.rb
class UserStorysController < ApplicationController
	before_action :find_userstorie, only: [:show, :edit, :update, :destroy]
	#before_action :find_projekt, only: [:new, :show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def index

		@projekt = Projekt.find(params[:projekt_id])
		@projekt_id = @projekt.id
		@userstorys = @projekt.user_stories
		
		 
	end


	def new
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@user_stories =  projekt.user_stories.build #UserStory.new
	end

	def create
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@userstory = projekt.user_stories.build(userstorie_params) #UserStory.new(userstorie_params)
    	if @userstory.save
    		
      		redirect_to user_storys_path(projekt_id: @projekt_id)
    	else
     		render 'new'  
    	end
	end


	def show
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
  	end

  	def edit
  		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
	end

	def update

		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		
		 if @userstory.status == 'done' && @userstory.finished_at == nil
  			@userstory.finished_at = DateTime.now
  			@userstory.save
  		 end
		
		
		if @userstory.update(userstorie_params)
			redirect_to user_story_path(@userstory,projekt_id: @projekt_id)
		else
			render 'edit'
		end
	end

	def destroy
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@userstory.destroy
  		redirect_to user_storys_path(projekt_id: @projekt_id)
	end


	def find_projekt
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
	end


	def find_userstorie
  		@userstory = UserStory.find(params[:id])
	end

	def userstorie_params
		params.require(:user_story).permit(:title, :description, :projekt_id, :sprintnumber, :status)
	end
end

app/helpers/user_storys_helper.rb
module UserStorysHelper
end

app/views/user_storys/edit.html.erb
<h1>User Story editieren </h1>


<div class = "formlay">

<%= simple_form_for @userstory, url: user_story_path(:projekt_id => @projekt_id)  do |f| %>
  <%= f.input :title, label: 'Titel' %>
  <%= f.input :description, label: 'Beschreibung' %>
  <%= f.input :sprintnumber, label: 'Sprintnummer'%>

  <div class="checkbox">
  	<%= f.collection_radio_buttons :status, [['backlog', 'Backlog'] ,['inProgress', 'In Progress'], ['review', 'Review'] ,['done', 'Done']],:first, :last %> 
  </div>


  

  <%= f.button :submit, "Editieren" %>
<% end %>

  </div>

app/views/user_storys/index.html.erb
<h1>Product Backlog</h1>
<button type="button" class="btn btn-default"><%= link_to "Neue User Story", new_user_story_path(projekt_id: @projekt_id) %></button>

<div class="row">

  		<div class="col-md-2 list">
  		 	<p class="ptitle">User Stories</p>
        	<% if @userstorys.count > 0  %>
          		<div class="listcard">
	      		 	<% @userstorys.each do |userstorie| %>
	      		 	 	<p><%= link_to userstorie.title, user_story_path(userstorie, projekt_id: @projekt_id) %> <br>
                  <% if userstorie.status == "done"%>
                    <span class = "status, badge"><%= userstorie.status %></span>
                  <% end %>                  
                </p>

	            	<% end %>
        		</div>
        	<% end %>
  		</div>
</div>

<div class = "crud">
			<p><%= link_to "Zurück", projekt_path(@projekt_id) %>
</div>

app/views/user_storys/new.html.erb
<h1> Neue User Story erstellen </h1>

    <%= simple_form_for @user_stories, url: user_storys_path(projekt_id: @projekt_id)  do |f| %>
      <%= f.input :title, label: 'Titel' %>
      <%= f.input :description, label: 'Beschreibung' %>




      <div class="button">
      <%= f.button :submit, "Erstellen" %>
      </div>
    <% end %> 


<div class = "crud">
			<p><%= link_to "Zurück", user_storys_path(projekt_id: @projekt_id) %>
</div>

app/views/user_storys/show.html.erb
<h2><%= @userstory.title %></h2>
<h2><%= @userstory.description %></h2>

<%if @finished_at != nil %>
	<p>finished ==> <%= @finished_at %> </p>
<% end %>

<%if @started_at != nil %>
	<p>start ==>  <%= @started_at %> </p>
<% end %>


<div class=crud>
	<%= link_to "Zurück", user_storys_path(projekt_id: @projekt_id) %>
	<%= link_to "Editieren", edit_user_story_path(@userstory, projekt_id: @projekt_id) %>
	<%=link_to "Löschen", user_story_path(@userstory, projekt_id: @projekt_id), method: :delete, data: { confirm: "Bist du sicher ?"} %>
	
</div>