config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projekts#index"

  #get ':projekt_id', to: 'user_storys#index'

  resources :projekts
  resources :user_storys 
  resources :sprints
  resources :scrumboards
  resources :planpokers 
  resources :burndowncharts
  resources :sprintplans
  resources :sprintreviews
  resources :sprintretros
  resources :roadmaps

  get '/createfields', to: "planpokers#createfields"
  post '/createfields', to: "planpokers#createfields"


  get '/checkpoker', to: "planpokers#checkpoker"
  post '/checkpoker', to: "planpokers#checkpoker"


  get '/pokersuccess', to: "planpokers#pokersuccess"
  post '/pokersuccess', to: "planpokers#pokersuccess"

  get '/setsprint', to: "sprintplans#setsprint"
  post '/setsprint', to: "sprintplans#setsprint"


  get '/setreview', to: "sprintreviews#setreview"
  post '/setreview', to: "sprintreviews#setreview"

  
  get '/setretros', to: "sprintretros#setretros"
  post '/setretros', to: "sprintretros#setretros"


  

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_backlog.rb
class ProductBacklog < ApplicationRecord
	belongs_to :projekt
end

app/models/projekt.rb
class Projekt < ApplicationRecord

	belongs_to :user
	has_many :user_stories
	has_many :sprints
end

app/models/sprint.rb
class Sprint < ApplicationRecord
	
	belongs_to :projekt
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :projekts
end

app/models/user_story.rb
class UserStory < ApplicationRecord
	belongs_to :projekt
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/planpokers_controller.rb
class PlanpokersController < ApplicationController
	rescue_from ActiveRecord::RecordNotFound, with: :dude_where_is_my_record

	def dude_where_is_my_record
		@projekt_id = params[:projekt_id]
		@userstory_id = params[:userstory_id]
    	flash[:notice] = "Dude where is my record !!!! no User Story with id = " + @userstory_id + "  ;-("
    	redirect_to planpokers_path(projekt_id: @projekt_id)
  	end

	def index
		@projekt = Projekt.find(params[:projekt_id])
		@projekt_id = params[:projekt_id]
		@userstories = @projekt.user_stories.where(estimation: nil)
	end

	def createfields
		@playernumber = params[:playernumber].to_i
		@projekt_id = params[:projekt_id] 
		@projekt = Projekt.find(params[:projekt_id])
		@userstory_id = params[:userstory_id].to_i
		@userstory = UserStory.find(@userstory_id)

		if @userstory.estimation != nil
			flash[:notice] = "Die User Story wurde schon eingeschätzt!! bitte nur vom Backlog auswählen"
			redirect_to planpokers_path(projekt_id: @projekt_id)

		else
			render 'createfields'
		end


	end

	def checkpoker

		@userstory_id = params[:userstory_id]
		@playernumber = params[:playernumber]
		@projekt_id = params[:projekt_id]
		

		@playernames = params[:playernames] 
		@playername1 = @playernames[0]
		@playername2 = @playernames[1]

		@estimations  = params[:estimations] 
		@estimation1 = @estimations[0]
		@estimation2 = @estimations[1]


		if @estimation1 == @estimation2
			@userstory = UserStory.find(@userstory_id)
			@userstory.estimation = @estimation1
			@userstory.save
			redirect_to pokersuccess_path(userstory_id: @userstory_id, projekt_id: @projekt_id, estimation: @estimation1)
		else
			flash[:notice] = "Die Einschätzungen waren unterschiedlich, diskutieren Sie bitte erneut und versuchen Sie es noch mal"
			redirect_to createfields_path(userstory_id: @userstory_id, projekt_id: @projekt_id, playernumber: @playernumber)
		end
	
	end

	
	def pokersuccess
		@projekt_id = params[:projekt_id]

	end


end

app/controllers/projekts_controller.rb
class ProjektsController < ApplicationController
	before_action :find_projekt, only: [:show, :edit, :update, :destroy, :getProjektId]
	before_action :authenticate_user!
	def index
		@projekts = current_user.projekts
	end

	def new
		@projekt = current_user.projekts.build
	end

	def create
		@projekt = current_user.projekts.build(projekt_params)
    	if @projekt.save
      		redirect_to root_path
    	else
     		render 'new'  #wenn es nicht klappt, die view new wird nochmal mit den eingegebenen Daten geladen, noch mal versuchen
    	end
	end

	def show
    @id = @projekt.id
  end

	def edit
	end

	def update
	if @projekt.update(projekt_params)
		redirect_to projekt_path(@projekt)
	else
		render 'edit'
	end
	end

	def destroy
		@projekt.destroy
  	redirect_to root_path
	end


  def find_projekt
  	@projekt = Projekt.find(params[:id])
	end

	def projekt_params
		params.require(:projekt).permit(:name)
	end

  def getProjektId
    redirect_to :controller => 'user_storys', :action => 'index', @projekt => @projekt
  end
end

app/controllers/roadmaps_controller.rb
class RoadmapsController < ApplicationController

	def index
		@projekt = Projekt.find(params[:format])
		@projekt_name = @projekt.name
	end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
	before_action :find_sprint, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	
	def index
		@projekt = Projekt.find(params[:projekt_id])
		@projekt_id = @projekt.id
		@sprints = Sprint.where(projekt_id: @projekt_id)
	end

	def new
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprints =  projekt.sprints.build
		
	end

	def create
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprint = projekt.sprints.build(sprint_params) #UserStory.new(userstorie_params)
    	if @sprint.save
      		redirect_to sprints_path(projekt_id: @projekt_id)
    	else
     		render 'new'  
    	end
	end

	def show 
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprint_id = params[:id] 
  	end

  	def edit
  		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
	end

	def update
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		if @sprint.update(sprint_params)
			redirect_to sprint_path(@sprint,projekt_id: @projekt_id)
		else
			render 'edit'
		end
	end

	def destroy
		projekt = Projekt.find(params[:projekt_id])
		@projekt_id = projekt.id
		@sprint.destroy
  		redirect_to sprints_path(projekt_id: @projekt_id)
	end







	def find_sprint
  		@sprint = Sprint.find(params[:id])
	end

	def sprint_params
		params.require(:sprint).permit(:sprintnumber)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burndowncharts_helper.rb
module BurndownchartsHelper
end

app/helpers/planpokers_helper.rb
module PlanpokersHelper
end

app/helpers/product_backlog_helper.rb
module ProductBacklogHelper
end

app/helpers/projekts_helper.rb
module ProjektsHelper
end

app/helpers/roadmaps_helper.rb
module RoadmapsHelper
end

app/helpers/scrumboards_helper.rb
module ScrumboardsHelper
end

app/helpers/sprintplans_helper.rb
module SprintplansHelper
end

app/helpers/sprintretros_helper.rb
module SprintretrosHelper
end

app/helpers/sprintreviews_helper.rb
module SprintreviewsHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/user_storys_helper.rb
module UserStorysHelper
end

app/views/projekts/edit.html.erb
<h1>Projekt editieren </h1>
<div class = "col-md-3">
	<%= simple_form_for @projekt do |f| %>
	  <%= f.input :name, label: "Projektname" %>
	  <%= f.button :submit, "Editieren" %>
	<% end %>
</div>

app/views/projekts/index.html.erb
<h1>Projekte</h1>

<button type="button" class="btn btn-default"><%= link_to "Neues Projekt", new_projekt_path %></button>


<% @projekts.each do |projekt| %>

        <div>
          <h2><%= link_to projekt.name, projekt %></h2>
        </div>

<% end %>

app/views/projekts/new.html.erb
<h1>Neues Projekt erstellen </h1>
<div class = "col-md-3">
	<%= simple_form_for @projekt do |f| %>
	  <%= f.input :name, label: "Projektname" %>
	  <%= f.button :submit, "Erstellen" %>
	<% end %>
</div>

app/views/projekts/show.html.erb
<h2><%= @projekt.name %></h2>


<p><%= link_to "Product Backlog", user_storys_path(projekt_id: @projekt.id) %></p>
<p><%= link_to "Sprints", sprints_path(projekt_id: @projekt.id) %></p>
<p><%= link_to "Plannigs Poker", planpokers_path(projekt_id: @projekt.id) %></p>
<p><%= link_to "Burn-down-chart", burndowncharts_path(@projekt) %></p>
<p><%= link_to "Roadmap", roadmaps_path(@projekt) %></p>

<div class=crud>
	<%= link_to "Zurück", root_path %>
	<%= link_to "Editieren", edit_projekt_path %>
	<%=link_to "Löschen", projekt_path(@projekt), method: :delete, data: { confirm: "Bist du sicher ?"} %>
</div>

app/views/sprints/edit.html.erb
<h1> neue sprint editieren </h1>

	<%= simple_form_for @sprints, url: sprints_path(projekt_id: @projekt_id)  do |f| %>
	  <%= f.input :sprintnumber %>
	  <%= f.button :submit, "Anlegen" %>
	<% end %>

<div class = "crud">
			<p><%= link_to "Zurück", projekt_path(@projekt_id) %>
</div>

app/views/sprints/index.html.erb
<h1>Meine Sprints</h1>
<button type="button" class="btn btn-default"><%= link_to "Neuer Sprint", new_sprint_path(projekt_id: @projekt_id) %></button>

<% @sprints.each do |sprint| %>

    <div>
      	<h2><%= link_to "Sprint" + " " + sprint.sprintnumber, sprint_path(sprint, projekt_id: @projekt_id) %></h2>
    </div>

        

<% end %>

<div class = "crud">
	<p><%= link_to "Zurück", projekt_path(@projekt_id) %>
</div>

app/views/sprints/new.html.erb
<h1> Neuen Sprint anlegen </h1>

<%= simple_form_for @sprints, url: sprints_path(projekt_id: @projekt_id)  do |f| %>
  <%= f.input :sprintnumber, label: 'Sprintnummer' %>
  <%= f.button :submit, "Anlegen", label: 'erstellen'  %>
<% end %>

<div class = "crud">
			<p><%= link_to "Zurück", sprint_path(@projekt_id) %>
</div>

app/views/sprints/show.html.erb
<h2><span> Sprint </span> <%=@sprint.sprintnumber%></h2> <br>

<div>
	<p><%= link_to "Sprint Planning", sprintplans_path(sprint_id: @sprint_id, projekt_id: @projekt_id) %></p>
	<p><%= link_to "Scrum Board", scrumboards_path(sprintnumber: @sprint.sprintnumber, projekt_id: @projekt_id) %></p>
	<p><%= link_to "Sprint Review", sprintreviews_path(sprint_id: @sprint_id, projekt_id: @projekt_id) %></p>
	<p><%= link_to "Sprint Retrospective", sprintretros_path(sprint_id: @sprint_id, projekt_id: @projekt_id) %></p>
</div>


<div class=crud>
	<%= link_to "Zurück", sprints_path(projekt_id: @projekt_id) %>
	<%=link_to "Löschen", sprint_path(@sprint, projekt_id: @projekt_id), method: :delete, data: { confirm: "Bist du sicher ?"} %>
	
</div>